ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_desktop'
ENV['VAGRANT_EXPERIMENTAL'] = 'disks'

Vagrant.configure("2") do |config|

    config.vm.define 'minecraft-bedrock' do |this_config|
        this_config.vm.box = "bento/ubuntu-22.04"
        this_config.vm.host_name = 'minecraft-bedrock'
        this_config.vm.provision :shell, inline: "apt-get update"
        #this_config.vm.provision :shell, inline: "apt-get upgrade"

        this_config.vm.provision :shell, path: "files/webmin.sh"
        this_config.vm.provision :shell, path: "files/tailscale.sh"
        this_config.vm.provision :shell, path: "files/minecraft.sh"

        this_config.vm.provider "vmware_desktop" do |v|
            v.vmx["memsize"]  = "8192"
            v.vmx["numvcpus"] = 2
            v.gui = true
            v.vmx["virtualhw.version"] = "19"
        end
    end
end
