ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_desktop'
ENV['VAGRANT_EXPERIMENTAL'] = 'disks'

Vagrant.configure("2") do |config|

    config.vm.define 'satisfactory' do |this_config|
        this_config.vm.box = "bento/ubuntu-22.04"
        this_config.vm.host_name = 'satisfactory'

        config.vm.provision "ansible_local" do |ansible|
            ansible.become = true
            ansible.playbook = "playbook.yml"
            ansible.config_file = "ansible.cfg"
            ansible.galaxy_role_file = "requirements.yml"
            ansible.galaxy_roles_path = "/etc/ansible/collections"
            ansible.galaxy_command = "sudo ansible-galaxy collection install --requirements-file=%{role_file} --collections-path=%{roles_path} --force"
        end

        this_config.vm.provider "vmware_desktop" do |v|
            v.vmx["memsize"]  = "8192"
            v.vmx["numvcpus"] = 2
            v.gui = true
            v.vmx["virtualhw.version"] = "19"
        end
    end
end

